// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tournament-controls/InlineHeaderActions.tsx": () => import("../components/mockups/tournament-controls/InlineHeaderActions.tsx"),
  "./components/mockups/tournament-controls/OrganizedSettings.tsx": () => import("../components/mockups/tournament-controls/OrganizedSettings.tsx"),
  "./components/mockups/tournament-controls/QuickActionsBar.tsx": () => import("../components/mockups/tournament-controls/QuickActionsBar.tsx")
};
